# Site wide configuration

title: 
locale: en_US
description: Cooking for everyday!
logo: site-logo.png
search: true
# url: http://localhost:4000
# Site live URL
url: http://weekendfamily.github.io/foodforthepeople

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: António Domingues
  avatar: bio-photo.jpg
  email: amjdomingues@gmail
  # disqus-shortname: fridaymeetssunday
  twitter: #username
  facebook: #username
  github: adomingues
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: +AntónioMigueldeJesusDomingues
    analytics: UA-60277379-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# comments
site:
  owner:
    disqus-shortname: weekendfamily-github-io

comments: true
